apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: jenkins
  template:
    metadata:
      name: jenkins
      labels:
        tier: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8081