apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: calebespinoza/store-products:3.0
        ports:
        - containerPort: 80
