apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0.31
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: none
      - name: MYSQL_DATABASE
        value: test
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"